enabled: true
titleOnly: true

scopes:
  - frontend
  - backend
  - terraform
  - docs
  - ci

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
