/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface CreateServiceRole {
	organisationId: number;
	name: string;
	releaseCreate: boolean;
	releaseApprove: boolean;
	releasePublish: boolean;
	releaseMetadataEdit: boolean;
	releaseLocalizedMetadataEdit: boolean;
}
