/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface CreateServiceUserRequest {
	serviceId: number;
	organisationUserId: number;
	serviceRoleId: number;
}
