/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface CreateReleaseTriggerRequest {
	name: string;
	event: string;
	url: string;
	serviceId: number;
}
