/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface CreateLocaleRequest {
  serviceId: number;
  languageCode: string;
  countryCode: string;
  isDefault?: boolean | null;
}
