/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface LocaleRecord {
  id?: number;
  languageCode?: string | null;
  countryCode?: string | null;
  isDefault?: boolean;
}
