/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface MetadataArrayElement {
	index?: number;
	name?: string | null;
	type?: string | null;
	label?: string | null;
	minLength?: number | null;
	maxLength?: number | null;
	required?: boolean;
}
