/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { DomainEventBase } from './domainEventBase';
import type { OrganisationUser } from './organisationUser';

export interface OrganisationRole {
	id?: number;
	updatedAt?: string;
	createdAt?: string;
	readonly domainEvents?: DomainEventBase[] | null;
	name: string;
	serviceWrite: boolean;
	serviceDelete: boolean;
	userRead: boolean;
	userWrite: boolean;
	userDelete: boolean;
	organisationId?: number;
	users?: OrganisationUser[] | null;
}
