/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface OrganisationUserRecord {
	id?: number;
	userId?: string | null;
	email?: string | null;
	firstName?: string | null;
	lastName?: string | null;
}
