/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { DomainEventBase } from './domainEventBase';
import type { OrganisationRole } from './organisationRole';
import type { ServiceUser } from './serviceUser';

export interface OrganisationUser {
	id?: number;
	updatedAt?: string;
	createdAt?: string;
	readonly domainEvents?: DomainEventBase[] | null;
	userId: string;
	email: string;
	firstName: string;
	lastName: string;
	lastSignIn?: string | null;
	organisationId?: number;
	role?: OrganisationRole;
	roleId?: number;
	serviceUser?: ServiceUser[] | null;
	isActive: boolean;
}
