/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */

export interface OrganisationRecord {
  id?: number;
  name?: string | null;
  routeName?: string | null;
  updatedAt?: string;
  createdAt?: string;
}
