/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { ReleaseRecordMetadata } from './releaseRecordMetadata';

export interface ReleaseRecord {
	version?: string | null;
	metadata?: ReleaseRecordMetadata;
	serviceId?: number;
	approvedBy?: number | null;
	approvedAt?: string | null;
	publishedBy?: number | null;
	publishedAt?: string | null;
}
