/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { ReleaseLocalisedMetadataRecord } from './releaseLocalisedMetadataRecord';

export interface ReleaseRecord {
	id?: number;
	version?: string | null;
	serviceId?: number;
	metadata?: string | null;
	localisedMetadata?: ReleaseLocalisedMetadataRecord[] | null;
	updatedAt?: string;
	createdAt?: string;
}
