/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { DomainEventBase } from './domainEventBase';
import type { Locale } from './locale';
import type { Release } from './release';

export interface ReleaseLocalisedMetadata {
	id?: number;
	updatedAt?: string;
	createdAt?: string;
	readonly domainEvents?: DomainEventBase[] | null;
	metadata: string;
	readonly releaseId: number;
	release?: Release;
	readonly localeId: number;
	locale?: Locale;
}
