/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { Locale } from './locale';
import type { ServiceUser } from './serviceUser';
import type { Release } from './release';
import type { ReleaseTarget } from './releaseTarget';

export interface ServiceRecord {
	serviceId?: number;
	name?: string | null;
	description?: string | null;
	locales?: Locale[] | null;
	serviceUsers?: ServiceUser[] | null;
	releases?: Release[] | null;
	releaseTargets?: ReleaseTarget[] | null;
	organisationId?: number;
}
