/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { DomainEventBase } from './domainEventBase';

export interface ServiceRole {
	id?: number;
	updatedAt?: string;
	createdAt?: string;
	readonly domainEvents?: DomainEventBase[] | null;
	name: string;
	releaseCreate: boolean;
	releaseApprove: boolean;
	releasePublish: boolean;
	releaseMetadataEdit: boolean;
	releaseLocalizedMetadataEdit: boolean;
}
