/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import type { UpdateReleaseLocalisedMetadata } from './updateReleaseLocalisedMetadata';

export interface UpdateReleaseRequest {
	releaseId?: number;
	metaData: string;
	localisedMetadataList: UpdateReleaseLocalisedMetadata[];
}
