version: "3.9"
services:
  postgresql:
    image: postgres:14.2-alpine
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "5432"]
      interval: 1s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgis-volume/data:/var/lib/postgresql/data
  srm:
    image: registry.k3s.devnico.cloud/service-release-manager:latest
    depends_on:
      postgresql:
        condition: service_healthy

    links:
      - "postgresql:db"
    environment:
      ASPNETCORE_ENVIRONMENT: PRODUCTION
      ASPNETCORE_Keycloak__Url: https://idp.srm.k3s.devnico.cloud
      ASPNETCORE_Keycloak__Realm: dev
      ASPNETCORE_Keycloak__SwaggerClientId: webapp-v1
      ASPNETCORE_Keycloak__ClientId: backend-client
      ASPNETCORE_Keycloak__ClientSecret: ecHkkh9ROE7wugVRZnb2O4Lj37ejh0v4
      ASPNETCORE_Keycloak__Audience: account
      DB_HOST: db
      DB_NAME: test
      DB_USER: test
      DB_PASSWORD: test
    ports:
      - 7024:5003