version: "3.9"
services:
  postgresql:
    image: postgres:14.2-alpine
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "5432"]
      interval: 1s
      timeout: 10s
      start_period: 30s
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgis-volume/data:/var/lib/postgresql/data