/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Service Release Manager API
 * OpenAPI spec version: v1
 */
import {
	useQuery,
	useMutation,
	UseQueryOptions,
	UseMutationOptions,
	QueryFunction,
	MutationFunction,
	UseQueryResult,
	QueryKey,
} from 'react-query';
import type {
	ReleaseRecord,
	CreateReleaseRequest,
	UpdateReleaseRequest,
} from '.././models';
import { customInstance, ErrorType } from '.././axios';

/**
 * Creates a new Release
 * @summary Creates a new Release
 */
export const releaseCreate = (createReleaseRequest: CreateReleaseRequest) => {
	return customInstance<ReleaseRecord>({
		url: `/releases`,
		method: 'post',
		headers: { 'Content-Type': 'application/json' },
		data: createReleaseRequest,
	});
};

export type ReleaseCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof releaseCreate>>
>;
export type ReleaseCreateMutationBody = CreateReleaseRequest;
export type ReleaseCreateMutationError = ErrorType<void>;

export const useReleaseCreate = <
	TError = ErrorType<void>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof releaseCreate>>,
		TError,
		{ data: CreateReleaseRequest },
		TContext
	>;
}) => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof releaseCreate>>,
		{ data: CreateReleaseRequest }
	> = (props) => {
		const { data } = props ?? {};

		return releaseCreate(data);
	};

	return useMutation<
		Awaited<ReturnType<typeof releaseCreate>>,
		TError,
		{ data: CreateReleaseRequest },
		TContext
	>(mutationFn, mutationOptions);
};
/**
 * Deletes a release
 * @summary Deletes a release
 */
export const releaseDelete = (releaseId: number) => {
	return customInstance<void>({
		url: `/releases/${releaseId}`,
		method: 'delete',
	});
};

export type ReleaseDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof releaseDelete>>
>;

export type ReleaseDeleteMutationError = ErrorType<unknown>;

export const useReleaseDelete = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof releaseDelete>>,
		TError,
		{ releaseId: number },
		TContext
	>;
}) => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof releaseDelete>>,
		{ releaseId: number }
	> = (props) => {
		const { releaseId } = props ?? {};

		return releaseDelete(releaseId);
	};

	return useMutation<
		Awaited<ReturnType<typeof releaseDelete>>,
		TError,
		{ releaseId: number },
		TContext
	>(mutationFn, mutationOptions);
};
/**
 * Gets a single Release by ReleaseId
 * @summary Gets a single Release
 */
export const releasesGetById = (releaseId: number, signal?: AbortSignal) => {
	return customInstance<ReleaseRecord>({
		url: `/releases/${releaseId}`,
		method: 'get',
		signal,
	});
};

export const getReleasesGetByIdQueryKey = (releaseId: number) => [
	`/releases/${releaseId}`,
];

export type ReleasesGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof releasesGetById>>
>;
export type ReleasesGetByIdQueryError = ErrorType<void>;

export const useReleasesGetById = <
	TData = Awaited<ReturnType<typeof releasesGetById>>,
	TError = ErrorType<void>
>(
	releaseId: number,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof releasesGetById>>,
			TError,
			TData
		>;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getReleasesGetByIdQueryKey(releaseId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof releasesGetById>>
	> = ({ signal }) => releasesGetById(releaseId, signal);

	const query = useQuery<
		Awaited<ReturnType<typeof releasesGetById>>,
		TError,
		TData
	>(queryKey, queryFn, { enabled: !!releaseId, ...queryOptions });

	return {
		queryKey,
		...query,
	};
};

/**
 * Updates a Release
 * @summary Updates a Release
 */
export const releaseUpdate = (
	releaseId: string,
	updateReleaseRequest: UpdateReleaseRequest
) => {
	return customInstance<ReleaseRecord>({
		url: `/releases/${releaseId}`,
		method: 'post',
		headers: { 'Content-Type': 'application/json' },
		data: updateReleaseRequest,
	});
};

export type ReleaseUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof releaseUpdate>>
>;
export type ReleaseUpdateMutationBody = UpdateReleaseRequest;
export type ReleaseUpdateMutationError = ErrorType<void>;

export const useReleaseUpdate = <
	TError = ErrorType<void>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof releaseUpdate>>,
		TError,
		{ releaseId: string; data: UpdateReleaseRequest },
		TContext
	>;
}) => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof releaseUpdate>>,
		{ releaseId: string; data: UpdateReleaseRequest }
	> = (props) => {
		const { releaseId, data } = props ?? {};

		return releaseUpdate(releaseId, data);
	};

	return useMutation<
		Awaited<ReturnType<typeof releaseUpdate>>,
		TError,
		{ releaseId: string; data: UpdateReleaseRequest },
		TContext
	>(mutationFn, mutationOptions);
};
