name: Backend Dev
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - ci/deployment
    # paths:
    #   - "backend/**"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/backend-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      branch: develop
