name: Backend Prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/backend-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      branch: main
