name: Backend Dev
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    uses: ./.github/workflows/backend-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      branch: develop
