name: Backend Dev
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "backend/**"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/backend-deploy.yml
    with:
      branch: develop
