name: Frontend Prod
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    uses: ./.github/workflows/frontend-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      branch: main
