name: Frontend Dev Deploy
"on":
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          access_token_scopes: "email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase"
          workload_identity_provider: "projects/827464709272/locations/global/workloadIdentityPools/gh-pool/providers/actions-provider"
          service_account: "gh-actions-deployment@service-release-manager.iam.gserviceaccount.com"
          create_credentials_file: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
        working-directory: "frontend"

      - run: npm run build
        working-directory: "frontend"

      - run: npx firebase-tools deploy --only hosting:develop --project service-release-manager
        working-directory: "frontend"
