name: Frontend Dev
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/frontend-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      branch: develop
